name = "hugo-theme-okome"
license = "MIT"
licenselink = "https://github.com/okomestudio/hugo-theme-okome/blob/master/LICENSE"
description = "Hugo theme for Biboroku"
homepage = "https://github.com/okomestudio/hugo-theme-okome/"
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Okome Studio"
  homepage = "https://github.com/okomestudio"
